vscode:
  extensions:
    - oderwat.indent-rainbow
    - mintlify.document
    - streetsidesoftware.code-spell-checker
    - tombonnike.vscode-status-bar-format-toggle
    - github.copilot
    - fivepointseven.node-version
    - kejun.devtoys
    - esbenp.prettier-vscode
    - visualstudioexptteam.vscodeintellicode
    - styled-components.vscode-styled-components
    - kejun.devtoys
    - qoretechnologies.qore-vscode
    - mattpocock.ts-error-translator
    - usernamehw.errorlens
tasks:
  - init: |
      nvm install v14.18
      npm install
    command: |
      nvm install v14.18
      git config --global http.sslverify false
      cd /workspace/qorus-vscode
      npm run start
additionalRepositories:
  - url: https://git.qoretechnologies.com/qorus/building-blocks
  - url: https://git.qoretechnologies.com/qorus/demos.git
  - url: https://git.qoretechnologies.com/qorus/qorus.git
