export const interfaceKindTransform = {
  'service-methods': 'service',
  step: 'step',
  'mapper-methods': 'mapper-code',
  error: 'errors',
  errors: 'errors',
  workflow: 'workflow',
  service: 'service',
  job: 'job',
  'mapper-code': 'mapper-code',
  mapper: 'mapper',
  group: 'group',
  event: 'event',
  queue: 'queue',
  connection: 'connection',
  fsm: 'fsm',
  pipeline: 'pipeline',
  'value-map': 'value-map',
  type: 'type',
  class: 'class',
};

export const interfaceToPlural = {
  service: 'services',
  step: 'steps',
  'mapper-code': 'mapper-codes',
  errors: 'errors',
  workflow: 'workflows',
  job: 'jobs',
  mapper: 'mappers',
  group: 'groups',
  event: 'events',
  queue: 'queues',
  connection: 'connections',
  fsm: 'fsms',
  pipeline: 'pipelines',
  'value-map': 'valuemaps',
  type: 'types',
  class: 'classes',
  'schema-module': 'schema-modules',
  script: 'scripts',
  test: 'tests',
};

export const interfaceIcons = {
  service: 'ServerLine',
  step: 'StickyNoteLine',
  'mapper-code': 'FunctionLine',
  errors: 'ErrorWarningLine',
  workflow: 'GitBranchLine',
  job: 'CalendarLine',
  mapper: 'MindMap',
  group: 'GridFill',
  event: 'GitCommitLine',
  queue: 'StackLine',
  connection: 'Plug2Line',
  fsm: 'DashboardLine',
  pipeline: 'NodeTree',
  'value-map': 'BringToFront',
  type: 'Asterisk',
  class: 'CodeSLine',
  'schema-module': 'Asterisk',
  script: 'Asterisk',
  test: 'Asterisk',
};

export const interfaceNameToKind = {
  Service: 'service',
  Step: 'step',
  'Mapper Code': 'mapper-code',
  Errors: 'errors',
  Workflow: 'workflow',
  Job: 'job',
  Mapper: 'mapper',
  Group: 'group',
  Event: 'event',
  Queue: 'queue',
  Connection: 'connection',
  'Flow Builder': 'fsm',
  Pipeline: 'pipeline',
  'Value Map': 'value-map',
  Type: 'type',
  Class: 'class',
  'Schema Module': 'schema-module',
  Script: 'script',
  Test: 'test',
};
