export const interfaceKindTransform = {
  'service-methods': 'service',
  step: 'step',
  'mapper-methods': 'mapper-code',
  error: 'errors',
  errors: 'errors',
  workflow: 'workflow',
  service: 'service',
  job: 'job',
  'mapper-code': 'mapper-code',
  mapper: 'mapper',
  group: 'group',
  event: 'event',
  queue: 'queue',
  connection: 'connection',
  fsm: 'fsm',
  pipeline: 'pipeline',
  'value-map': 'value-map',
  type: 'type',
  class: 'class',
};
