export const interfaceKindTransform = {
  'service-methods': 'service',
  step: 'step',
  'mapper-methods': 'mapper-code',
  error: 'errors',
  errors: 'errors',
  workflow: 'workflow',
  service: 'service',
  job: 'job',
  'mapper-code': 'mapper-code',
  mapper: 'mapper',
  group: 'group',
  event: 'event',
  queue: 'queue',
  connection: 'connection',
  fsm: 'fsm',
  pipeline: 'pipeline',
  'value-map': 'value-map',
  type: 'type',
  class: 'class',
};

export const interfaceToPlural = {
  service: 'services',
  step: 'steps',
  'mapper-code': 'mapper-codes',
  errors: 'errors',
  workflow: 'workflows',
  job: 'jobs',
  mapper: 'mappers',
  group: 'groups',
  event: 'events',
  queue: 'queues',
  connection: 'connections',
  fsm: 'fsms',
  pipeline: 'pipelines',
  'value-map': 'valuemaps',
  type: 'types',
  class: 'classes',
};
